name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "b1a9738a-7081-4efc-ac11-b87f5fe0d774" \
            --password "LuQ8Q~VkO9u5GVHRFzFsjYiO1k7LjsG6h_UXgcFl" \
            --tenant "4e86bdd1-0efb-47f9-a76d-517388c5e28f"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "c14887df-3ce2-44d2-adb8-4405e7e105d8"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "b1a9738a-7081-4efc-ac11-b87f5fe0d774" \
            --password "LuQ8Q~VkO9u5GVHRFzFsjYiO1k7LjsG6h_UXgcFl" \
            --tenant "4e86bdd1-0efb-47f9-a76d-517388c5e28f"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "c14887df-3ce2-44d2-adb8-4405e7e105d8"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
